<a href="https://colab.research.google.com/github/bilaltahir99/test-repo/blob/master/Forecasting_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.layers import Dense, Input, GlobalMaxPooling1D
from tensorflow.keras.layers import LSTM, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.callbacks import ModelCheckpoint

np.random.seed(0)
tf.random.set_seed(0)

In [ ]:
df = pd.read_csv('FORECASTING.txt', index_col=False)
df = df.sort_values(by=['ACTIVITY_DATE'],ascending=True)
df.drop(['YEAR_','MONTH_','DAY_','HOUR_'],axis=1,inplace=True)
for a in range(len(df)):
  df['ACTIVITY_DATE'][a]= df.ACTIVITY_DATE[a][:-7]
df = df.set_index(['ACTIVITY_DATE'])
df.info()

In [62]:
Ntest=720
train = df.iloc[:-Ntest]
test = df.iloc[-Ntest:]

In [63]:
# Obtain these by inspecting the files
T = 7
Ntrain=102135
Ntest=720
D = 3 # since there 3 parallel time series
#K = 3 # number of classes (1-6)

In [64]:
train

                                    EUTRANCELLFDD  ...  DOWNL_PRB_AVG_UTLZN
ACTIVITY_DATE                                      ...
01/01/2021 00:00:00            QTA0503L_6_ARPR_SS  ...                   61
01/01/2021 00:00:00  LHR7600L_3_MakroMarketLinkRd  ...                    8
01/01/2021 00:00:00             KHI0555L_3_BINQSM  ...                   27
01/01/2021 00:00:00         GJK9486L_31_BurjiStop  ...                    3
01/01/2021 00:00:00             KHK60894L_3_CHMRD  ...                   74
...                                           ...  ...                  ...
31/08/2021 16:00:00             KHK60894L_3_CHMRD  ...                   25
31/08/2021 16:00:00           KHI61037L_3_GMAYAMR  ...                   18
31/08/2021 16:00:00             KHI0555L_3_BINQSM  ...                   64
31/08/2021 16:00:00                    RWP8445L_3  ...                   27
31/08/2021 17:00:00            QTA0503L_6_ARPR_SS  ...                   42

[102135 rows x 4 columns]